export const SPANISH_PROVINCES = [
  "Álava",
  "Albacete",
  "Alicante",
  "Almería",
  "Asturias",
  "Ávila",
  "Badajoz",
  "Baleares",
  "Barcelona",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cantabria",
  "Castellón",
  "Ceuta",
  "Ciudad Real",
  "Córdoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Guipúzcoa",
  "Huelva",
  "Huesca",
  "Jaén",
  "La Coruña",
  "La Rioja",
  "Las Palmas",
  "León",
  "Lleida",
  "Lugo",
  "Madrid",
  "Málaga",
  "Melilla",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
] as const

export type SpanishProvince = (typeof SPANISH_PROVINCES)[number]

export const VIA_TYPES = [
  { value: "CALLE", label: "Calle" },
  { value: "AVENIDA", label: "Avenida" },
  { value: "PLAZA", label: "Plaza" },
  { value: "PASEO", label: "Paseo" },
  { value: "CAMINO", label: "Camino" },
  { value: "CARRETERA", label: "Carretera" },
  { value: "RONDA", label: "Ronda" },
  { value: "TRAVESIA", label: "Travesía" },
  { value: "GLORIETA", label: "Glorieta" },
  { value: "OTROS", label: "Otros" },
] as const
