import Navbar from "../../components/navbar"
import Footer from "../../components/footer"
import BagDetail from "../../components/bag-detail"

export default function BagDetailPage({ params }: { params: { id: string } }) {
  // Base de datos de bolsos con IDs que coinciden exactamente con catalog-section.tsx
  const bagsDatabase: { [key: string]: any } = {
    "lv-pont-neuf-pm": {
      id: "lv-pont-neuf-pm",
      name: "Pont-Neuf PM",
      brand: "Louis Vuitton",
      description:
        "El bolso Pont-Neuf de Louis Vuitton es un clásico atemporal confeccionado en cuero Epi, reconocible por su textura acanalada característica. Este modelo combina elegancia y funcionalidad con su diseño estructurado, asas dobles y herrajes dorados. Su interior espacioso cuenta con múltiples compartimentos, ideal para organizar tus pertenencias diarias.",
      price: "129€/mes",
      retailPrice: "2.450€",
      images: ["/images/lv-pont-neuf-main.jpeg", "/images/lv-pont-neuf-detail.jpeg", "/images/lv-pont-neuf-side.jpeg"],
      membership: "signature" as const,
      color: "Negro",
      material: "Cuero Epi",
      dimensions: "25 x 18 x 10 cm",
      condition: "Excelente",
      year: "2018",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 127,
      features: [
        "Diseño icónico de Louis Vuitton",
        "Cuero Epi de alta calidad con textura acanalada",
        "Herrajes dorados que no se oxidan",
        "Interior espacioso con múltiples compartimentos",
        "Asas dobles para mayor comodidad",
        "Cierre con cremallera seguro",
        "Perfecto para uso diario y ocasiones especiales",
      ],
      careInstructions: [
        "Limpiar con un paño suave y seco",
        "Evitar el contacto con agua y líquidos",
        "Guardar en su dust bag original cuando no se use",
        "Evitar la exposición directa al sol por períodos prolongados",
        "No usar productos químicos o limpiadores abrasivos",
        "Rellenar con papel de seda para mantener la forma",
      ],
    },
    "lv-epi-wallet-chain": {
      id: "lv-epi-wallet-chain",
      name: "Pochette Félicie Epi",
      brand: "Louis Vuitton",
      description:
        "Elegante cartera con cadena en cuero Epi multicolor. Diseño versátil que funciona como clutch de noche o bolso crossbody. Interior organizado con múltiples compartimentos y acabados en tonos rosa y coral.",
      price: "129€/mes",
      retailPrice: "1.450€",
      images: [
        "/images/lv-epi-wallet-front.jpeg",
        "/images/lv-epi-wallet-side.jpeg",
        "/images/lv-epi-wallet-interior.jpeg",
      ],
      membership: "signature" as const,
      color: "Rojo coral multicolor",
      material: "Cuero Epi",
      dimensions: "21 x 12 x 3 cm",
      condition: "Excelente",
      year: "2020",
      availability: { status: "available" as const },
      rating: 4.9,
      reviews: 89,
      features: [
        "Diseño versátil 2 en 1",
        "Cuero Epi multicolor exclusivo",
        "Cadena desmontable",
        "Múltiples compartimentos organizados",
        "Perfecto para día y noche",
        "Tamaño compacto y elegante",
      ],
      careInstructions: [
        "Limpiar con un paño suave y seco",
        "Evitar el contacto con agua",
        "Guardar en su dust bag original",
        "Cuidar la cadena de rayones",
      ],
    },
    "lv-reverie": {
      id: "lv-reverie",
      name: "Rêverie",
      brand: "Louis Vuitton",
      description:
        "Bolso bucket en cuero marrón con detalles dorados y correa ajustable. Diseño versátil y elegante perfecto para el día a día.",
      price: "59€/mes",
      retailPrice: "1.350€",
      images: [
        "/images/lv-reverie-front.jpeg",
        "/images/lv-reverie-closure-detail.jpeg",
        "/images/lv-reverie-main.jpeg",
      ],
      membership: "essentiel" as const,
      color: "Marrón",
      material: "Cuero",
      dimensions: "26 x 24 x 18 cm",
      condition: "Excelente",
      year: "2019",
      availability: { status: "available" as const },
      rating: 4.7,
      reviews: 156,
      features: [
        "Diseño bucket clásico",
        "Cuero de alta calidad",
        "Correa ajustable",
        "Amplio espacio interior",
        "Cierre con cordón",
        "Versatilidad día/noche",
      ],
      careInstructions: [
        "Limpiar con un paño suave",
        "Hidratar el cuero ocasionalmente",
        "Evitar la humedad excesiva",
        "Guardar relleno para mantener forma",
      ],
    },
    "marni-trunk-mini": {
      id: "marni-trunk-mini",
      name: "Trunk Mini",
      brand: "Marni",
      description:
        "Bolso crossbody en cuero rosa pálido con herrajes dorados. Diseño minimalista y sofisticado con compartimentos internos organizados.",
      price: "59€/mes",
      retailPrice: "890€",
      images: ["/images/marni-front-view.jpeg", "/images/marni-side-view.jpeg", "/images/marni-interior-detail.jpeg"],
      membership: "essentiel" as const,
      color: "Rosa pálido",
      material: "Cuero",
      dimensions: "20 x 15 x 8 cm",
      condition: "Excelente",
      year: "2021",
      availability: { status: "available" as const },
      rating: 4.6,
      reviews: 73,
      features: [
        "Diseño minimalista italiano",
        "Color rosa pálido único",
        "Herrajes dorados",
        "Tamaño perfecto para crossbody",
        "Interior organizado",
        "Estilo contemporáneo",
      ],
      careInstructions: [
        "Limpiar con paño húmedo suave",
        "Evitar roces con superficies ásperas",
        "Proteger del sol directo",
        "Guardar en lugar seco",
      ],
    },
    "patou-geometric-bag": {
      id: "patou-geometric-bag",
      name: "Le Patou Geometric",
      brand: "PATOU",
      description:
        "Bolso de diseño geométrico en cuero beige con forma semicircular distintiva. Correa ajustable y herrajes dorados.",
      price: "59€/mes",
      retailPrice: "950€",
      images: [
        "/images/patou-front-view-real.jpeg",
        "/images/patou-interior-detail-real.jpeg",
        "/images/patou-logo-detail.jpeg",
      ],
      membership: "essentiel" as const,
      color: "Beige",
      material: "Cuero",
      dimensions: "22 x 15 x 8 cm",
      condition: "Excelente",
      year: "2022",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 45,
      features: [
        "Diseño geométrico único",
        "Forma semicircular distintiva",
        "Cuero beige versátil",
        "Correa ajustable",
        "Estilo arquitectónico",
        "Marca francesa emergente",
      ],
      careInstructions: [
        "Limpiar con paño seco",
        "Mantener forma geométrica",
        "Evitar presión excesiva",
        "Guardar en posición correcta",
      ],
    },
    "lv-epi-yellow-handbag": {
      id: "lv-epi-yellow-handbag",
      name: "Malesherbes Epi",
      brand: "Louis Vuitton",
      description:
        "Elegante bolso Louis Vuitton en cuero Epi amarillo vibrante. Diseño clásico con asa superior y cierre plateado.",
      price: "189€/mes",
      retailPrice: "2.950€",
      images: [
        "/images/lv-epi-yellow-front-real.jpeg",
        "/images/lv-epi-yellow-interior-real.jpeg",
        "/images/lv-epi-yellow-logo-detail.jpeg",
      ],
      membership: "prive" as const,
      color: "Amarillo",
      material: "Cuero Epi",
      dimensions: "24 x 18 x 12 cm",
      condition: "Excelente",
      year: "2017",
      availability: { status: "available" as const },
      rating: 4.9,
      reviews: 34,
      features: [
        "Color amarillo vibrante exclusivo",
        "Cuero Epi texturizado",
        "Interior burgundy contrastante",
        "Herrajes plateados premium",
        "Diseño clásico atemporal",
        "Pieza de colección",
      ],
      careInstructions: [
        "Limpiar solo con paño seco",
        "Proteger del contacto con otros colores",
        "Guardar en dust bag original",
        "Evitar exposición prolongada al sol",
      ],
    },
    "celine-teen-triumph": {
      id: "celine-teen-triumph",
      name: "Teen Triumph",
      brand: "Céline",
      description:
        "Elegante bolso crossbody de Céline en cuero suave rosa nude. Diseño minimalista con el icónico logo dorado y correa ajustable. Perfecto para el día a día con un toque de sofisticación parisina.",
      price: "129€/mes",
      retailPrice: "2.100€",
      images: [
        "/images/celine-teen-triumph-front.jpeg",
        "/images/celine-teen-triumph-interior.jpeg",
        "/images/celine-teen-triumph-detail.jpeg",
      ],
      membership: "signature" as const,
      color: "Rosa nude",
      material: "Cuero suave",
      dimensions: "19 x 14 x 4.5 cm",
      condition: "Excelente",
      year: "2021",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 92,
    },
    "loewe-gate": {
      id: "loewe-gate",
      name: "Gate",
      brand: "Loewe",
      description:
        "El icónico bolso Gate de Loewe en cuero granulado marrón. Diseño arquitectónico con correas entrelazadas que crean la característica 'puerta'. Artesanía española excepcional con forro en ante suave.",
      price: "129€/mes",
      retailPrice: "2.200€",
      images: ["/images/loewe-gate-front.jpeg", "/images/loewe-gate-texture.jpeg", "/images/loewe-gate-interior.jpeg"],
      membership: "signature" as const,
      color: "Marrón",
      material: "Cuero granulado",
      dimensions: "24 x 20 x 10 cm",
      condition: "Excelente",
      year: "2020",
      availability: { status: "available" as const },
      rating: 4.7,
      reviews: 112,
    },
    "gucci-jackie": {
      id: "gucci-jackie",
      name: "Jackie",
      brand: "Gucci",
      description:
        "El legendario bolso Jackie de Gucci en canvas GG Supreme con detalles en cuero marrón. Incluye la icónica banda Web verde y roja, y el característico cierre tipo gancho dorado. Un clásico reinventado.",
      price: "129€/mes",
      retailPrice: "2.500€",
      images: [
        "/images/gucci-jackie-front.jpeg",
        "/images/gucci-jackie-interior.jpeg",
        "/images/gucci-jackie-label.jpeg",
      ],
      membership: "signature" as const,
      color: "GG Supreme con marrón",
      material: "Canvas GG Supreme",
      dimensions: "30 x 22 x 11 cm",
      condition: "Excelente",
      year: "2022",
      availability: { status: "available" as const },
      rating: 4.9,
      reviews: 68,
    },
    "prada-hobo": {
      id: "prada-hobo",
      name: "Hobo Bag",
      brand: "Prada",
      description:
        "Elegante bolso hobo de Prada en cuero marrón cognac con forma de media luna. Diseño sofisticado con el icónico triángulo dorado y correa ajustable. Artesanía italiana excepcional con forro negro de lujo.",
      price: "129€/mes",
      retailPrice: "2.200€",
      images: [
        "/images/prada-hobo-front.jpeg",
        "/images/prada-hobo-interior-1.jpeg",
        "/images/prada-hobo-interior-2.jpeg",
      ],
      membership: "signature" as const,
      color: "Marrón cognac",
      material: "Cuero",
      dimensions: "22 x 13.5 x 6 cm",
      condition: "Excelente",
      year: "2023",
      availability: { status: "available" as const },
      rating: 4.6,
      reviews: 135,
    },
    "prada-bucket-saffiano": {
      id: "prada-bucket-saffiano",
      name: "Bucket Saffiano",
      brand: "Prada",
      description:
        "Bolso bucket de Prada en el icónico cuero Saffiano verde. Diseño funcional con cordón de cierre, compartimento principal espacioso y el distintivo triángulo dorado. Una pieza versátil para el día a día.",
      price: "129€/mes",
      retailPrice: "2.000€",
      images: [
        "/images/prada-bucket-saffiano-front.jpeg",
        "/images/prada-bucket-saffiano-logo.jpeg",
        "/images/prada-bucket-saffiano-interior.jpeg",
      ],
      membership: "signature" as const,
      color: "Verde Saffiano",
      material: "Cuero Saffiano",
      dimensions: "22 x 22 x 13.5 cm",
      condition: "Excelente",
      year: "2021",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 79,
    },
    "fendi-ff-logo-pouch": {
      id: "fendi-ff-logo-pouch",
      name: "FF Logo Pouch",
      brand: "Fendi",
      description:
        "Elegante pouch de Fendi en cuero negro suave con el icónico logo FF dorado prominente. Diseño contemporáneo con textura fruncida y cadena dorada ajustable. Perfecto como clutch o crossbody.",
      price: "129€/mes",
      retailPrice: "2.300€",
      images: [
        "/images/fendi-ff-logo-front.jpeg",
        "/images/fendi-ff-logo-side.jpeg",
        "/images/fendi-ff-logo-detail.jpeg",
      ],
      membership: "signature" as const,
      color: "Negro con logo dorado",
      material: "Cuero suave",
      dimensions: "31.5 x 21 x 10 cm",
      condition: "Excelente",
      year: "2022",
      availability: { status: "available" as const },
      rating: 4.5,
      reviews: 95,
    },
    "loewe-gate-mini": {
      id: "loewe-gate-mini",
      name: "Gate Mini",
      brand: "Loewe",
      description:
        "La versión compacta del icónico Gate de Loewe en cuero beige. Mantiene el diseño distintivo de correas entrelazadas en un tamaño perfecto para ocasiones especiales. Correa con logo tejido incluida.",
      price: "59€/mes",
      retailPrice: "1.500€",
      images: [
        "/images/loewe-gate-mini-front.jpeg",
        "/images/loewe-gate-mini-interior.jpeg",
        "/images/loewe-gate-mini-logo.jpeg",
      ],
      membership: "essentiel" as const,
      color: "Beige",
      material: "Cuero suave",
      dimensions: "20 x 13 x 8 cm",
      condition: "Excelente",
      year: "2023",
      availability: { status: "available" as const },
      rating: 4.7,
      reviews: 54,
    },
    "prada-structured-bag": {
      id: "prada-structured-bag",
      name: "Structured Bag",
      brand: "Prada",
      description:
        "Bolso estructurado de Prada en cuero negro con diseño minimalista y sofisticado. El icónico triángulo dorado centra el diseño, mientras que su forma compacta lo hace perfecto para ocasiones especiales.",
      price: "59€/mes",
      retailPrice: "1.600€",
      images: [
        "/images/prada-structured-front.jpeg",
        "/images/prada-structured-interior.jpeg",
        "/images/prada-structured-logo.jpeg",
      ],
      membership: "essentiel" as const,
      color: "Negro",
      material: "Cuero",
      dimensions: "28.5 x 13.5 x 6.5 cm",
      condition: "Excelente",
      year: "2022",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 87,
    },
    "lady-dior": {
      id: "lady-dior",
      name: "Lady Dior",
      brand: "Dior",
      description:
        "El icónico bolso Lady Dior en cuero cannage negro con forro rojo vibrante. Incluye los característicos charms dorados 'D-I-O-R' y asas estructuradas. Una pieza de alta costura francesa que simboliza elegancia atemporal.",
      price: "189€/mes",
      retailPrice: "4.200€",
      images: ["/images/lady-dior-front.jpeg", "/images/lady-dior-interior.jpeg", "/images/lady-dior-charm.jpeg"],
      membership: "prive" as const,
      color: "Negro con forro rojo",
      material: "Cuero Cannage",
      dimensions: "24 x 20 x 11 cm",
      condition: "Excelente",
      year: "2021",
      availability: { status: "available" as const },
      rating: 4.9,
      reviews: 42,
    },
    "fendi-peekaboo": {
      id: "fendi-peekaboo",
      name: "Peekaboo",
      brand: "Fendi",
      description:
        "El legendario bolso Peekaboo de Fendi en cuero camel con forro FF signature. Diseño arquitectónico con el característico cierre metálico dorado y compartimentos internos. Una obra maestra de la artesanía italiana.",
      price: "189€/mes",
      retailPrice: "4.000€",
      images: [
        "/images/fendi-peekaboo-front.jpeg",
        "/images/fendi-peekaboo-side.jpeg",
        "/images/fendi-peekaboo-interior.jpeg",
      ],
      membership: "prive" as const,
      color: "Camel",
      material: "Cuero",
      dimensions: "31.5 x 21 x 10 cm",
      condition: "Excelente",
      year: "2020",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 31,
    },
    "fendi-croissant": {
      id: "fendi-croissant",
      name: "Croissant",
      brand: "Fendi",
      description:
        "El emblemático bolso Croissant de Fendi en cuero blanco con el logo FENDI en relieve dorado. Diseño icónico de los 2000s que ha regresado como símbolo de estatus. Forma de media luna distintiva con asa superior y correa ajustable.",
      price: "189€/mes",
      retailPrice: "3.000€",
      images: [
        "/images/fendi-croissant-front.jpeg",
        "/images/fendi-croissant-handle.jpeg",
        "/images/fendi-croissant-interior.jpeg",
      ],
      membership: "prive" as const,
      color: "Blanco",
      material: "Cuero",
      dimensions: "28 x 16.5 x 9 cm",
      condition: "Excelente",
      year: "2023",
      availability: { status: "available" as const },
      rating: 4.7,
      reviews: 63,
    },
    "fendi-saddle": {
      id: "fendi-saddle",
      name: "Saddle Bag",
      brand: "Fendi",
      description:
        "El icónico bolso Saddle de Fendi en cuero rosa con el distintivo logo FF dorado. Diseño revolucionario que redefinió la moda de bolsos con su forma única de silla de montar. Una pieza de colección contemporánea.",
      price: "129€/mes",
      retailPrice: "2.500€",
      images: [
        "/images/fendi-saddle-front.jpeg",
        "/images/fendi-saddle-interior.jpeg",
        "/images/fendi-saddle-back.jpeg",
      ],
      membership: "signature" as const,
      color: "Rosa",
      material: "Cuero",
      dimensions: "19 x 15 x 5 cm",
      condition: "Excelente",
      year: "2023",
      availability: { status: "available" as const },
      rating: 4.7,
      reviews: 63,
    },
    "dior-saddle": {
      id: "dior-saddle",
      name: "Saddle Bag",
      brand: "Dior",
      description:
        "El revolucionario bolso Saddle de Dior en cuero beige, diseñado por John Galliano. Una pieza que redefinió la moda de bolsos con su forma única inspirada en las sillas de montar. Símbolo de la alta costura francesa contemporánea.",
      price: "189€/mes",
      retailPrice: "3.600€",
      images: ["/images/dior-saddle-front.jpeg", "/images/dior-saddle-label.jpeg", "/images/dior-saddle-side.jpeg"],
      membership: "prive" as const,
      color: "Beige",
      material: "Cuero",
      dimensions: "24 x 18 x 7 cm",
      condition: "Excelente",
      year: "2022",
      availability: { status: "available" as const },
      rating: 4.9,
      reviews: 58,
    },
    "dior-vanity-case": {
      id: "dior-vanity-case",
      name: "Vanity Case",
      brand: "Dior",
      description:
        "Elegante neceser Vanity Case de Dior en cuero cannage beige con logo Christian Dior en relieve. Diseño funcional y sofisticado con compartimentos organizados y cremallera dorada. Perfecto para viajes o como bolso de noche.",
      price: "189€/mes",
      retailPrice: "3.300€",
      images: ["/images/dior-vanity-front.jpeg", "/images/dior-vanity-label.jpeg", "/images/dior-vanity-interior.jpeg"],
      membership: "prive" as const,
      color: "Beige cannage",
      material: "Cuero Cannage",
      dimensions: "18.5 x 13 x 10 cm",
      condition: "Excelente",
      year: "2023",
      availability: { status: "available" as const },
      rating: 4.8,
      reviews: 27,
    },
    "chanel-classic-flap": {
      id: "chanel-classic-flap",
      name: "Classic Flap",
      brand: "Chanel",
      description:
        "El legendario bolso Classic Flap de Chanel en cuero negro acolchado con forro rojo burgundy. La pieza más icónica de la maison con su cadena dorada entrelazada y el distintivo cierre CC. Una inversión atemporal en elegancia francesa.",
      price: "189€/mes",
      retailPrice: "5.500€",
      images: [
        "/images/chanel-classic-flap-front.jpeg",
        "/images/chanel-classic-flap-back.jpeg",
        "/images/chanel-classic-flap-interior.jpeg",
      ],
      membership: "prive" as const,
      color: "Negro con forro rojo",
      material: "Cuero acolchado",
      dimensions: "22 x 17.5 x 6 cm",
      condition: "Excelente",
      year: "2021",
      availability: { status: "available" as const },
      rating: 5.0,
      reviews: 19,
    },
  }

  const bagDetail = bagsDatabase[params.id]

  // Si no se encuentra el bolso, mostrar error
  if (!bagDetail) {
    return (
      <>
        <Navbar />
        <main className="pt-20 min-h-screen flex items-center justify-center">
          <div className="text-center">
            <h1 className="text-2xl font-serif text-slate-900 mb-4">Bolso no encontrado</h1>
            <p className="text-slate-600 mb-8">El bolso que buscas no existe o ha sido removido.</p>
            <a href="/catalog" className="bg-indigo-dark text-white px-6 py-3 rounded hover:bg-indigo-dark/90">
              Volver al Catálogo
            </a>
          </div>
        </main>
        <Footer />
      </>
    )
  }

  return (
    <>
      <Navbar />
      <main className="pt-20">
        <BagDetail bag={bagDetail} />
      </main>
      <Footer />
    </>
  )
}
